### ISSUE TITLE
msl and smap dataset preprocess gives error

### ISSUE THREAD

**Issue by naveedAnjumMian** [ML4ITS/mtad-gat-pytorch#34]
(venv) PS C:\Users\hp\PycharmProjects\mtad-gat-pytorch> python preprocess.py --dataset SMAP
SMAP test_label (427617,)
Traceback (most recent call last):                                                                                
  File "C:\Users\hp\PycharmProjects\mtad-gat-pytorch\preprocess.py", line 96, in <module>                         
    load_data(ds)                                                                                                 
  File "C:\Users\hp\PycharmProjects\mtad-gat-pytorch\preprocess.py", line 89, in load_data                        
    concatenate_and_save(c)                                                                                       
  File "C:\Users\hp\PycharmProjects\mtad-gat-pytorch\preprocess.py", line 81, in concatenate_and_save             
    temp = np.load(path.join(dataset_folder, category, filename + ".npy"))                                        
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                        
  File "C:\Users\hp\PycharmProjects\mtad-gat-pytorch\venv\Lib\site-packages\numpy\lib\npyio.py", line 427, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))                                                        
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                         
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/data\\train\\A-1.npy'

**Comment by axeloh** [comment]
Did you download the data? Only the SMD dataset comes as part of this repo.

**Comment by naveedAnjumMian** [comment]
now the problem is solved by downloading other datasets. Thanks
